[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[context.production.environment]
  SECRETS_SCAN_ENABLED = "false"

[context.deploy-preview.environment]
  SECRETS_SCAN_ENABLED = "false"

[context.branch-deploy.environment]
  SECRETS_SCAN_ENABLED = "false"